name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Instalar JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Construir con Maven
      run: mvn clean package -DskipTests

    - name: Guardar paquete generado para el trabajo de despliegue
      uses: actions/upload-artifact@v4
      with:
        name: moviecards-java
        path: "${{ github.workspace }}/target/*.jar"
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
    
      - name: Instalar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      
      - name: Instalar Chrome y ChromeDriver para pruebas end to end
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          
          sudo apt --fix-broken install -y
          
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          
          curl -L -o chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          
          unzip chromedriver.zip
          
          chmod +x chromedriver
          
          sudo mv chromedriver /usr/local/bin/
      
      - name: Ejecutar la aplicación para pruebas end to end
        run: mvn spring-boot:run & sleep 60
      
      - name: Ejecutar las pruebas unitarias, de integración y end to end
        run: mvn clean verify
 
  qa:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Análisis de SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=tu_proyecto_key \
            -Dsonar.organization=tu_organizacion \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.qualitygate.wait=true
  
  stage:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - name: Descargar paquete
        uses: actions/download-artifact@v4
        with:
          name: moviecards-java
          path: drop_stage
      - name: Deploy a Pre-Producción
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'moviecards-pre-albert-calugar'
          publish-profile: ${{ secrets.AZURE_STAGE_PUBLISHPROFILE }}
          package: 'drop_stage/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: stage
    if: github.ref=='refs/heads/master'
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
  
    steps:
      - name: Aprobación manual
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TOKEN }}
          approvers: AlexAlbert12
        
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: moviecards-java
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_589B8D33718D4CACBD94F8A8D2A4C4CA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_98787287B7054C6E99105F6BE5834526 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6DB0D990A30441D9AF868EC46149C170 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'moviecards-Albert-Calugar'
          slot-name: 'Production'
          package: '*.jar'
          